meta:
  engine: 4.2.1
  name: &name "travis-ergogen-2026"
  version: &meta_version "2026.01.19"
  date: "2026-01-19"
  author: 'Travis Hardiman'
  url: &url https://github.com/dieseltravis/travis-ergogen-2026
  tags: [ "ergogen", "keyboard", "cherrymx", "hotswap" ]
  cool_font: &cool_font "3270 Nerd Font"
units:
  kp: U + 2
  kspr: U + 1
  bp: kp/2 + 4
  sp: 1
  st: 1
  # stabs
  stabilizer_width: 7
  stabilizer_height: 16
  stabilizer_offset: 0 # This means south stabs, use `orient` to rotate them for north facing scenarios
  stabilizer_spacing_3u: U * ((3 - 1) / 2)
  stabilizer_spacing_2u: 23.86 / 2 # 0.94in / 2
points:
  zones:
    matrix:
      anchor:
        # move the PCB into view for KiCad
        shift: [50, -200]
      key:
        padding: kp
        spread: kspr
        #splay: 0
        tags:
          - key
      columns:
        col0:
          key:
            tags: col_even
            splay: 3sp
            stagger: 0st
            column_net: col0
          rows:
            row0:
              shift: [0.5kspr, 0.0kp]
              width: 2U
              rotate: 1
              tags:
                - row_even
                - key
                - 2u_stabilizers
              key:
                led_next: LED_37
                led_this: LED_36
            row1:
              shift: [-0.5kspr, 0.0kp]
              rotate: -1
              key:
                led_next: LED_36
                led_this: LED_35
            row2:
              key:
                led_next: LED_23
                led_this: LED_22
            row3:
              key:
                led_next: LED_22
                led_this: LED_21
            row4:
              key:
                led_next: LED_9
                led_this: LED_8
            row5:
              key:
                led_next: LED_8
                led_this: LED_7
        col1:
          key:
            tags: col_odd
            splay: -sp
            stagger: st
            column_net: col1
          rows:
            row0:
              skip: true
              #key:
              #  led_next: LED_38
              #  led_this: LED_37
            row1:
              key:
                led_next: LED_35
                led_this: LED_34
            row2:
              key:
                led_next: LED_24
                led_this: LED_23
            row3:
              key:
                led_next: LED_21
                led_this: LED_20
            row4:
              key:
                led_next: LED_10
                led_this: LED_9
            row5:
              key:
                led_next: LED_7
                led_this: LED_6
        col2:
          key:
            tags: col_even
            splay: -sp
            stagger: st
            column_net: col2
          rows:
            row0:
              key:
                #led_next: LED_39
                #led_this: LED_38
                led_next: LED_38
                led_this: LED_37
            row1:
              key:
                led_next: LED_34
                led_this: LED_33
            row2:
              key:
                led_next: LED_25
                led_this: LED_24
            row3:
              key:
                led_next: LED_20
                led_this: LED_19
            row4:
              key:
                led_next: LED_11
                led_this: LED_10
            row5:
              key:
                led_next: LED_6
                led_this: LED_5
        col3:
          key:
            tags: col_odd
            splay: -sp
            stagger: st
            column_net: col3
          rows:
            row0:
              key:
                #led_next: LED_40
                #led_this: LED_39
                led_next: LED_39
                led_this: LED_38
            row1:
              key:
                led_next: LED_33
                led_this: LED_32
            row2:
              key:
                led_next: LED_26
                led_this: LED_25
            row3:
              key:
                led_next: LED_19
                led_this: LED_18
            row4:
              key:
                led_next: LED_12
                led_this: LED_11
            row5:
              key:
                led_next: LED_5
                led_this: LED_4
        col4:
          key:
            tags: col_even
            splay: -sp
            stagger: -st
            column_net: col4
          rows:
            row0:
              key:
                #led_next: LED_41
                #led_this: LED_40
                led_next: LED_40
                led_this: LED_39
            row1:
              key:
                led_next: LED_32
                led_this: LED_31
            row2:
              key:
                led_next: LED_27
                led_this: LED_26
            row3:
              key:
                led_next: LED_18
                led_this: LED_17
            row4:
              key:
                led_next: LED_13
                led_this: LED_12
            row5:
              key:
                led_next: LED_4
                led_this: LED_3
        col5:
          key:
            tags: col_odd
            splay: -sp
            stagger: -st
            column_net: col5
          rows:
            row0:
              skip: true
              #key:
              #  led_next: LED_42
              #  led_this: LED_41
            row1:
              key:
                led_next: LED_31
                led_this: LED_30
            row2:
              key:
                led_next: LED_28
                led_this: LED_27
            row3:
              key:
                led_next: LED_17
                led_this: LED_16
            row4:
              key:
                led_next: LED_14
                led_this: LED_13
            row5:
              key:
                led_next: LED_3
                led_this: LED_2
        col6:
          key:
            tags: col_even
            splay: -sp
            stagger: -st
            column_net: col6
          rows:
            row0:
              shift: [-0.5kspr, 0.0kp]
              width: 2U
              rotate: -1
              tags:
                - row_even
                - key
                - 2u_stabilizers
              key:
                led_next: ""
                #led_this: LED_42
                led_this: LED_40
            row1:
              shift: [0.5kspr, 0.0kp]
              rotate: 1
              key:
                led_next: LED_30
                led_this: LED_29
            row2:
              key:
                led_next: LED_29
                led_this: LED_28
            row3:
              key:
                led_next: LED_16
                led_this: LED_15
            row4:
              key:
                led_next: LED_13
                led_this: LED_14
            row5:
              key:
                led_next: LED_2
                led_this: LED_1
      rows:
        row0:
          tags:
            - key
            - row_even
          row_net: row0
        row1:
          tags:
            - key
            - row_odd
          row_net: row1
        row2:
          tags:
            - key
            - row_even
          row_net: row2
        row3:
          tags:
            - key
            - row_odd
          row_net: row3
        row4:
          tags:
            - key
            - row_even
          row_net: row4
        row5:
          tags:
            - key
            - row_odd
          row_net: row5
outlines:
  raw:
  - what: rectangle
    where: true
    size: [kp + 2, kp + 2]
  2u_stabilizer: # This creates the stabilizer, you just need to use its name in a `where` clause of another outline
  - operation: stack
    where: 2u_stabilizers # Set this tag on the keys you want
    what: rectangle
    size: [stabilizer_width, stabilizer_height]
    adjust:
      shift: [stabilizer_spacing_2u, stabilizer_offset]
  - operation: stack
    where: 2u_stabilizers
    what: rectangle
    size: [stabilizer_width, stabilizer_height]
    adjust:
      shift: [-stabilizer_spacing_2u, stabilizer_offset]
  keys:
  - what: rectangle
    where: key
    size: [kp - 2, kp - 2]
  board:
    - what: polygon
      operation: stack
      fillet: 2.75
      points:
        - ref: matrix_col0_row0
          shift: [-bp - 0.5kspr, -bp]
        - ref: matrix_col3_row0
          shift: [-bp/3, -bp]

        - ref: matrix_col3_row0
          shift: [bp/3, -bp]
        - ref: matrix_col6_row0
          shift: [bp + 0.5kspr, -bp]

        - ref: matrix_col6_row5
          shift: [bp, bp + 20]
        #- ref: matrix_col3_row5
        #  shift: [bp/3, bp + 20]
        - ref: matrix_col6_row5
          shift: [0, bp + 20]
        - ref: matrix_col5_row5
          shift: [0, bp + 20]
        - ref: matrix_col4_row5
          shift: [0, bp + 20]
        - ref: matrix_col3_row5
          shift: [0, bp + 20]
        - ref: matrix_col2_row5
          shift: [0, bp + 20]
        - ref: matrix_col1_row5
          shift: [0, bp + 20]
        - ref: matrix_col0_row5
          shift: [0, bp + 20]
        #- ref: matrix_col3_row5
        #  shift: [-bp/3, bp + 20]
        - ref: matrix_col0_row5
          shift: [-bp, bp + 20]
  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  travis_erg2026:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:

      mcu:
        what: travis/ScottoKeebs-RP2040_Pro_Micro
        where:
          ref: matrix_col6_row5
          shift: [-3.5, kp + 0.5]
          rotate: -90
        params:
          value: "RP2040 Pro Micro"
          # left
          #P1:       # GP10
          #P2:       # GP0  D3 TXO/PD3
          #P3:       # GP1  D2 RXI/PD2
          P4: GND
          P5: GND
          P6: sda    # D1 SDA
          P7: scl    # D0 SCL PWM
          P8: row0   # D4 A6
          P9: row1   # C6 PWM
          P10: row2  # D7 A7 PWM
          P11: row3  # E6
          P12: row4  # B4 A8
          P13: row5  # B5 A9 PWM
          # bottom
          P14: GP12
          P15: GP13
          P16: GP14
          P17: GP15
          P18: GP16
          # right (from top)
          #P31:      # GP11
          #P30:      # RAW 5V
          P29: GND
          #P28:      # RESET 13
          #P27:      # VCC 3.3V
          P26: col6  # F4 A3
          P25: col5  # F5 A2
          P24: col4  # F6 A1
          P23: col3  # F7 A0
          P22: col2  # B1 SCLK
          P21: col1  # B3 MISO
          P20: col0  # B2 MOSI
          P19: LED_1 # B6 A10 PWM
          offset3d: [0, 0, 5]

      cap1:
        what: travis/CRadialD63H11P25
        params:
          P1: VCC
          P2: GND
          side: F
          bend: 90
          value: "6.3V 1000uF"
        where:
          ref: matrix_col6_row5
          shift: [3, kp - 0.5]
          rotate: 90

      # oled mounting options
      oled1:
        what: oled
        params:
          side: "F"
          SDA: sda
          SCL: scl
        where:
          ref: matrix_col0_row5
          shift: [-kp / 2, kp + 7.5]
          rotate: 0
      oled2:
        what: oled
        params:
          side: "F"
          SDA: sda
          SCL: scl
        where:
          #ref.aggregate.parts: [matrix_col1_row5, matrix_col2_row5]
          ref: matrix_col1_row5
          shift: [-kp / 4 - 0.75, kp / 2]
          rotate: 90
      oled3:
        what: oled
        params:
          side: "F"
          SDA: sda
          SCL: scl
        where:
          #ref.aggregate.parts: [matrix_col1_row5, matrix_col2_row5]
          ref: matrix_col1_row5
          shift: [kp / 4 + 0.75, kp + 13]
          rotate: 273
      oled4:
        what: oled
        params:
          side: "F"
          SDA: sda
          SCL: scl
        where:
          ref: matrix_col3_row5
          shift: [-kp / 4 - 0.75, kp / 2]
          rotate: 90
      oled5:
        what: oled
        params:
          side: "F"
          SDA: sda
          SCL: scl
        where:
          ref: matrix_col3_row5
          shift: [kp / 4 + 0.75, kp + 13]
          rotate: 270

      # keys
      mx_hotswap_key:
        what: travis/mx
        where: meta.tags ~ /key/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          refpos: [3.5, -2, 0]
          from: "{{column_net}}"
          to: "{{name}}"
          value: "Kailh MX Switch Sockets"
        adjust:
          rotate: 180
      diode:
        what: travis/DSMD_1206_3216Metric
        where: meta.tags ~ /key/
        params:
          side: B
          from: "{{name}}"
          to: "{{row_net}}"
          refpos: [-1.5, 2.75, 0]
        adjust:
          #shift: [-(U / 2 - 1.1), -(U / 2 - 1.5 - 1.9)]
          shift: [-(U / 2 - 3.5), -(U / 2 - 1)]
          rotate: 90

      # leds
      led_odd:
        what: travis/led_sk6812mini-e
        where: meta.tags ~ /row_odd/
        params:
          P1: "VCC"
          P2: "{{key.led_next}}" # DOUT: next P4
          P3: "GND"
          P4: "{{key.led_this}}" # DIN: previous P2 or pro micro data pin
          valpos: [0, 2.25]
          include_keepout: true
        adjust:
          shift: [0, -(-4.96)]
          rotate: 180
      ledlabel_odd:
        what: ceoloide/utility_text
        where: meta.tags ~ /row_odd/
        params:
          text: "{{key.led_this}}"
          reversible: true
          height: 1.0
          width: 1.0
        adjust:
          shift:  [0, -(-4.96 - 2.4)]
      ledcap_odd: # 104
        what: travis/CSMD_1206_3216Metric
        where: meta.tags ~ /row_odd/
        params:
          side: B
          refpos: [-1.5, 2.75, 0]
          valpos: [-2.5, 0]
        adjust:
          shift: [-4.75, 4.25]
          rotate: 270

      led_even:
        what: travis/led_sk6812mini-e
        where: meta.tags ~ /row_even/
        params:
          P1: "VCC"
          P2: "{{key.led_next}}" # DOUT: next P4
          P3: "GND"
          P4: "{{key.led_this}}" # DIN: previous P2 or pro micro data pin
          valpos: [0, 2.25]
          include_keepout: true
        adjust:
          shift: [0, -(-4.96)]
          rotate: 0
      ledlabel_even:
        what: ceoloide/utility_text
        where: meta.tags ~ /row_even/
        params:
          text: "{{key.led_this}}"
          reversible: true
          height: 1.0
          width: 1.0
        adjust:
          shift:  [0, -(-4.96 - 2.4)]
          rotate: 0
      ledcap_even: # 104
        what: travis/CSMD_1206_3216Metric
        where: meta.tags ~ /row_even/
        params:
          side: B
          refpos: [-1.5, 2.75, 0]
          valpos: [-2.5, 0]
        adjust:
          shift: [4.75, 5.65]
          rotate: 90

      # stabs
      left2u:
        what: travis/ScottoKeebs-Stabilizer_MX_2u
        where:
          ref: matrix_col0_row0
          shift: [0, 0]
          rotate: 0
      right2u:
        what: travis/ScottoKeebs-Stabilizer_MX_2u
        where:
          ref: matrix_col6_row0
          shift: [0, 0]
          rotate: 0

      # logos
      ergologo:
        what: ceoloide/utility_ergogen_logo
        where:
          ref: matrix_col2_row5
        params:
          scale: 2.0
        adjust:
          shift: [0, kp]
      travis:
        what: travis/travis
        where:
          ref: matrix_col4_row5
        params:
          scale: 3.0
        adjust:
          shift: [0, kp]
      roc:
        what: travis/roc
        where:
          ref: matrix_col0_row5
        params:
          side: "B"
          scale: 0.15
        adjust:
          shift: [0, kp]
      roclove:
        what: ceoloide/utility_text
        where:
          ref: matrix_col0_row5
        params:
          face: *cool_font
          text: "made with â™¥ in #ROC"
          mirrored: true
          side: "B"
          height: 1.1
          width: 1.1
        adjust:
          shift: [0, kp/2]
      name:
        what: ceoloide/utility_text
        where:
          ref: matrix_col3_row5
        params:
          face: *cool_font
          text: *name
          height: 2.5
          width: 2.5
          #align: "center"
          bold: true
        adjust:
          shift: [0, kp]
      url:
        what: ceoloide/utility_text
        where:
          ref: matrix_col3_row5
        params:
          text: *url
          #align: "right"
          side: B
          mirrored: true
        adjust:
          shift: [0, kp]
      version:
        what: ceoloide/utility_text
        where:
          ref: matrix_col3_row5
        params:
          face: *cool_font
          text: *meta_version
          height: 1.0
          width: 1.0
          #align: "center"
        adjust:
          shift: [0, kp - 2]
      pcbnumber:
        what: ceoloide/utility_text
        where:
          ref.aggregate.parts: [matrix_col3_row0, matrix_col3_row1]
        params:
          text: JLCJLCJLCJLC
          #text: WayWayWay
          reversible: true
        adjust:
          shift: [0, 0]
          rotate: 0

      # holes:
      holeTopLeft:
        what: travis/mountinghole
        where:
          ref: matrix_col0_row5
          shift: [-bp + 2.75, bp + 20 - 2.75]
        params:
          pad: 1
      holeTopRight:
        what: travis/mountinghole
        where:
          ref: matrix_col6_row5
          shift: [bp - 2.75 - 1, bp + 20 - 2.75 - 10]
        params:
          pad: 2
      holeBottomRight:
        what: travis/mountinghole
        where:
          ref: matrix_col6_row0
          shift: [bp + 0.5kspr - 2.75, -bp + 2.75]
        params:
          pad: 3
      holeBottomLeft:
        what: travis/mountinghole
        where:
          ref: matrix_col0_row0
          shift: [-bp - 0.5kspr + 2.75, -bp + 2.75]
        params:
          pad: 4

      # grounds
      background:
        what: ceoloide/utility_filled_zone
        params:
          side: "B"
          name: "back ground"
          connect_pads: "yes"
          points: [[15, 45], [195, 45], [195, 220], [15, 220]]
      foreground:
        what: ceoloide/utility_filled_zone
        params:
          side: "F"
          name: "fore ground"
          connect_pads: "yes"
          fill_type: "hatch"
          hatch_orientation: 45
          points: [[20, 50], [200, 50], [200, 225], [20, 225]]

cases:
